[build]
  command = ""  # no build command because it's a static site
  publish = "." # deploy from root folder

[context.production.environment]
  OPENWEATHER_API_KEY = "5c08a887f729315ff422e81a471ea0c3"

[context.deploy-preview.environment]
  OPENWEATHER_API_KEY = "5c08a887f729315ff422e81a471ea0c3"
